### ISSUE TITLE
Capture exception traceback from remote

### ISSUE THREAD

**Issue by ooq** [pywren/pywren#77]
We capture the internal exception from wrenhandler, but did not include traceback information in the response.

**Comment by ericmjonas** [comment]
@ooq For some reason I thought we did this, or am I misunderstanding? https://github.com/pywren/pywren/blob/master/pywren/jobrunner.py#L50  

Do you have a snippet of code that shows the problem and the desired behavior?

**Comment by ooq** [comment]
@ericmjonas Ah, right. I found a remote exception without traceback. I though it's from user program, but it's actually from wrenhandler.py. 
We should also propagate traceback for exceptions in wrenhandler.py. I'll change the description of this issue.

**Comment by ericmjonas** [comment]
The challenge with the traceback (and even the exception) -- you'll note that unlike our attempts to pickle the exception inside `jobrunner.py`, we can never be guaranteed the python version on the client is correct, so `reraise` isn't going to be very helpful here. 

Would pretty-printing a traceback into a string and returning that be enough, since we can't get a "real" traceback?

**Comment by ooq** [comment]
Yeah, I'm thinking just to add another field in `response_status` with something like `traceback.format_exc()` when we catch the exception in wrenhandler. I don't think we need to propagate the actual exception.
